# Generated by Django 4.0.1 on 2022-01-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_id', models.IntegerField()),
                ('drink_cname', models.CharField(max_length=20)),
                ('drink_Mmoney', models.IntegerField()),
                ('drink_Lmoney', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=10)),
                ('size', models.CharField(choices=[('M', '中'), ('L', '大')], default='M', max_length=2)),
                ('drink', models.CharField(choices=[('00', '挑Tea紅茶'), ('01', '蘭香綠茶'), ('02', '桂香烏龍茶'), ('03', '金萱青茶'), ('04', '極品高山茶'), ('05', '特級奶綠'), ('06', '芝麻奶茶'), ('07', '蜂蜜奶茶'), ('08', '烏龍奶茶'), ('09', '錫蘭奶紅'), ('10', '桔茶'), ('11', '葡萄柚汁'), ('12', '金桔檸檬'), ('13', '蘆薈蜂蜜檸檬'), ('14', '鳳梨紅茶'), ('15', '珍珠/波霸奶茶'), ('16', '暗黑水晶奶茶'), ('17', '椰果奶茶'), ('18', '蘆薈優多綠茶'), ('19', '紅茶三兄弟')], default='00', max_length=10)),
            ],
            options={
                'ordering': ['-oid'],
            },
        ),
    ]
